DATASET:
  IMAGE_SIZE: 384
  PATCH_SIZE: 64
  PATCH_SIZE_RATIO: 1
  IMG_BOX: /home/nibou/Documents/Master_thesis_Euresys/EasyCounting/model/utils/orange_box.txt
  IMG_PATH: /home/nibou/Documents/Master_thesis_Euresys/EasyCounting/model/utils/orange.jpg
  TILING_P: 0.5
MODEL:
  BACKBONE_MODEL: DefaultExp
  EMB_DIM: 256
  KERNEL_DIM: 3
  LAST_LAYER: layer4
  MODEL_NAME: EasyCounting_64
  MODEL_PATH: /home/nibou/Documents/Master_thesis_Euresys/EasyCounting/model/checkpoints/easycounting_64.pt
  NB_CHANNEL: 64
  NUM_DECODER_LAYERS: 0
  NUM_ENC_LAYERS: 3
  NUM_HEADS: 8
  NUM_OBJECTS: 3
  NUM_OPE_ITERATIVE_STEPS: 0
  PADDING: true
  REDUCTION: 8
  SCALE_AS_KEY: false
  SCALE_ONLY: false
  TRAINABLE_REFERENCES: false
  TRAINABLE_ROTATION: false
  TRAINABLE_ROT_NB_BLOCKS: 1
TRAINING:
  MODE: demo # demo, train or test
  DEVICE: cuda:0
  PRINT_NETWORK_STATS: false

  AUX_WEIGHT: 0.3
  BACKBONE_LR: 0
  BATCH_SIZE: 1
  DROPOUT: 0.1
  EPOCH: 100
  LEARNING_RATE: 0.0001
  LR_DROP: 200
  MAX_GRAD_NORM: 0.1
  PRENORM: true
  WEIGHT_DECAY: 0.0001
