DATASET:
  ANNOTATION_FILE: annotation.json
  DATA_PATH: /mnt/grodisk-nvme/Nicolas_student/Image_orin/Small_nails_32/images_68
  GT_FOLDER: gt_density_map
  IMAGE_FOLDER: images
  IMAGE_SIZE: 384
  PATCH_SIZE: 32
  PATCH_SIZE_RATIO: 1
  SPLIT_FILE: split.json
  TEST_DATA: Small_nails_32_68
  TILING_P: 0.5
MODEL:
  BACKBONE_MODEL: DefaultExp
  EMB_DIM: 256
  KERNEL_DIM: 3
  LAST_LAYER: layer4
  MODEL_NAME: adapted_loca_p_ope_rot_1
  MODEL_PATH: /mnt/grodisk-nvme/Nicolas_student/deepcounting/adapted_loca/checkpoints/AdaptedLocaExp/adapted_loca_32_p_ope_rot_1.pt
  NB_CHANNEL: 64
  NUM_DECODER_LAYERS: 0
  NUM_ENC_LAYERS: 3
  NUM_HEADS: 8
  NUM_OBJECTS: 3
  NUM_OPE_ITERATIVE_STEPS: 3
  PADDING: true
  REDUCTION: 8
  SCALE_AS_KEY: false
  SCALE_ONLY: false
  TRAINABLE_REFERENCES: false
  TRAINABLE_ROTATION: true
  TRAINABLE_ROT_NB_BLOCKS: 1
TRAINING:
  AUX_WEIGHT: 0.3
  BACKBONE_LR: 0
  BATCH_SIZE: 4
  DEVICE: cuda:0
  DROPOUT: 0.1
  EPOCH: 100
  EVALUATE: true
  FIRST: false
  LEARNING_RATE: 0.0001
  LR_DROP: 200
  MAX_GRAD_NORM: 0.1
  PRENORM: true
  TRAIN: false
  USE_FIRST: false
  WEIGHT_DECAY: 0.0001
