DATASET:
  ANNOTATION_FILE: annotation.json
  DATA_PATH: /home/nibou/Documents/Master_thesis_Euresys/data/FSCindu
  GT_FOLDER: gt_density_map
  IMAGE_FOLDER: images
  IMAGE_SIZE: 384
  PATCH_SIZE: 32
  PATCH_SIZE_RATIO: 1
  SPLIT_FILE: split.json
  TEST_DATA: test_FSC_indu
  TILING_P: 0.5
MODEL:
  BACKBONE_MODEL: MobileNetV3
  EMB_DIM: 256
  KERNEL_DIM: 3
  LAST_LAYER: layer4
  MODEL_NAME: MobileCount_32
  MODEL_PATH: /home/nibou/Documents/Master_thesis_Euresys/EasyCounting/model/checkpoints/mobilecount_32.pt
  NB_CHANNEL: 64
  NUM_DECODER_LAYERS: 0
  NUM_ENC_LAYERS: 3
  NUM_HEADS: 8
  NUM_OBJECTS: 3
  NUM_OPE_ITERATIVE_STEPS: 3
  PADDING: true
  REDUCTION: 8
  SCALE_AS_KEY: false
  SCALE_ONLY: false
  TRAINABLE_REFERENCES: false
  TRAINABLE_ROTATION: true # /!\ work only with kernel == 3
  TRAINABLE_ROT_NB_BLOCKS: 1
TRAINING:
  MODE: test # demo, train or test
  DEVICE: cuda:0
  PRINT_NETWORK_STATS: false

  AUX_WEIGHT: 0.3
  BACKBONE_LR: 0
  BATCH_SIZE: 4
  DROPOUT: 0.1
  EPOCH: 50
  LEARNING_RATE: 0.0001
  LR_DROP: 200
  MAX_GRAD_NORM: 0.1
  PRENORM: true
  WEIGHT_DECAY: 0.0001
