DATASET:
  ANNOTATION_FILE: annotation.json
  DATA_PATH: /mnt/grodisk-nvme/Nicolas_student/FSC147
  GT_FOLDER: gt_density_map_adaptive_384_384_object_VarV2
  IMAGE_FOLDER: images
  IMAGE_SIZE: 384
  PATCH_SIZE: 32
  PATCH_SIZE_RATIO: 1
  SPLIT_FILE: split.json
  TILING_P: 0.5
  TRAINING_DATA: train
MODEL:
  BACKBONE_MODEL: DefaultExp
  DECODER_LAYERS: 3
  EMB_DIM: 256
  KERNEL_DIM: 3
  LAST_LAYER: layer4
  NUM_DECODER_LAYERS: 0
  NUM_ENC_LAYERS: 3
  NUM_HEADS: 8
  NUM_OBJECTS: 3
  NUM_OPE_ITERATIVE_STEPS: 0
  PADDING: false
  REDUCTION: 8
  ROTATION: false
  SAVING_NAME: adapted_loca_32
  SCALE_AS_KEY: false
  SCALE_ONLY: false
  TRAINABLE_REFERENCES: false
  TRAINABLE_ROTATION: false
  TRAINABLE_ROT_NB_BLOCKS: 1
TRAINING:
  AUX_WEIGHT: 0.3
  BACKBONE_LR: 0
  BATCH_SIZE: 4
  DEVICE: cpu
  DROPOUT: 0.1
  EPOCH: 100
  EVALUATE: false
  FIRST: false
  LEARNING_RATE: 0.0001
  LR_DROP: 200
  MAX_GRAD_NORM: 0.1
  PRENORM: true
  TRAIN: true
  USE_FIRST: false
  WEIGHT_DECAY: 0.0001
